### ISSUE TITLE
Unclear which file will be generated

### ISSUE THREAD

**Issue by mislav** [andyfeller/gh-ssh-allowed-signers#1]
I ran the command and it seemed successful but I couldn't tell what got saved where. I needed to look at the source code to see that the data was stored in `~/.ssh/allowed_signers`. Is this a standard location of some kind? If not, how come it's a default for the tool?

Should the user instead have to always provide the path for the destination file? Or, better yet, the command could just output the email + pubkey combo to standard output and have the user choose what to do with the output. For example:

```
gh ssh-allowed-signers >> ~/.ssh/allowed_signers
```

Thanks for this great tool!

**Comment by andyfeller** [comment]
Doh, thanks for the feedback, @mislav!

🤔 This is a bit of a toughie.  Though the location of this file is mentioned in the help usage _(see below)_, I agree that it should tell you that once the extension completes.

```shell
$ gh ssh-allowed-signers --help

Generate SSH allowed signers file from GitHub users.

USAGE
  gh-ssh-allowed-signers [options] <organization>/<team>
  gh-ssh-allowed-signers [options] <user>

FLAGS
  -a, --append                        Append signing keys to existing SSH allowed signers file
  -d, --debug                         Enable debugging
  -f, --force                         Whether to overwrite output file if it exists
  -o, --output-file <output-file>     Path to SSH allowed signers file to generate; default '/Users/andyfeller/.ssh/allowed_signers'
```

If the file exists, it will fail to overwrite it unless you use `-f, --force`, however I think at the least it should tell you the file it will create.

**Comment by andyfeller** [comment]
@mislav : just finished pushing up a small change that should hopefully make this clearer:

```shell
$ gh ssh-allowed-signers github/ps-delivery
Using SSH allowed signers file:  /Users/andyfeller/.ssh/allowed_signers

Error: /Users/andyfeller/.ssh/allowed_signers exists; -f, --force will delete if exists

Generate SSH allowed signers file from GitHub users.

USAGE
  gh-ssh-allowed-signers [options] <organization>/<team>
  gh-ssh-allowed-signers [options] <user>

FLAGS
  -a, --append                        Append signing keys to existing SSH allowed signers file
  -d, --debug                         Enable debugging
  -f, --force                         Whether to overwrite output file if it exists
  -o, --output-file <output-file>     Path to SSH allowed signers file to generate; default '/Users/andyfeller/.ssh/allowed_signers'


$ gh ssh-allowed-signers -f github/ps-delivery
Using SSH allowed signers file:  /Users/andyfeller/.ssh/allowed_signers
Deleting existing SSH allowed signers file:  /Users/andyfeller/.ssh/allowed_signers
Pulling signing keys for team:  github/ps-delivery
Pulling signing keys for user:  ...
```

Since it seemed like a bit of community was trying to standardize on default file location I use, I want to encourage the convention but allow people to override it if they really want.  I'll keep mind open as cases develop to see how this should change, but I truly appreciate the feedback :bow:
